package ar.edu.utn.frc.tup.piii.engine.effects.trainers;

import ar.edu.utn.frc.tup.piii.engine.effects.trainers.chain.TrainerContext;
import ar.edu.utn.frc.tup.piii.models.cards.effects.trainer.TrainerEffect;
import ar.edu.utn.frc.tup.piii.models.game.BoardState;

import java.util.List;
import ar.edu.utn.frc.tup.piii.events.GameEvent;

/**
 * Flyweight interface for executing trainer effects.
 *
 * @param <T> The specific type of TrainerEffect this logic handles.
 */
public interface TrainerEffectLogic<T extends TrainerEffect> {

    /**
     * Executes the trainer effect.
     *
     * @param effectData The data transfer object mapped from the JSON.
     * @param ctx        Execution context: board, playerId, and cardLookup.
     * @return A list of events generated by this effect.
     */
    List<GameEvent> execute(T effectData, TrainerContext ctx);

    /**
     * Legacy adapter: delegates to {@link #execute(TrainerEffect, TrainerContext)}.
     * Kept for backward compatibility with direct callers (e.g. CoinFlipTrainerLogic sub-effect dispatch).
     */
    default List<GameEvent> execute(T effectData, BoardState board, Long playerId) {
        TrainerContext ctx = TrainerContext.builder()
                .board(board)
                .playerId(playerId)
                .build();
        return execute(effectData, ctx);
    }
}
